# This is the standard conda configuration file. Use this file to list
# the conda packages that you need installed in your environment.
channels:
  - conda-forge
dependencies:
  - python=3.12
  - rust
  - maturin
  - gcc_linux-64
  - gxx_linux-64
  - libgcc-ng
  - compilers
  - binutils
  - pip
  - uv
